### Handling Imbalanced Dataset

In [1]:
import pandas as pd
df=pd.read_csv('creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [2]:
df.shape

(284807, 31)

In [3]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [4]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [5]:
#### Independent and dependent Features
x=df.drop('Class',axis=1)
y=df.Class

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix


In [7]:
10.0 **np.arange(-2,3)

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [8]:
log_class=LogisticRegression()
## cross validation (hyper parameter tuning) i really want to check just because of hyper parameters will there be any type of impact on the model on the imbalanced dataset whether i am able to perform well.
grid={'C':10.0 **np.arange(-2,3),'penalty':['l1','l2']}
# cross validation of KFold
cv = KFold(n_splits=5,random_state=None,shuffle=False)

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,train_size=0.7)

In [10]:
clf = GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

E:\anaconda\lib\site-packages\sklearn\model_selection\_search.py:921: UserWarning: One or more of the test scores are non-finite: [       nan 0.82317191        nan 0.84286482        nan 0.84729531
        nan 0.85059248        nan 0.85253685]
  category=UserWarning
E:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [11]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85262    48]
 [   58    75]]
0.9987594068560327
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85310
           1       0.61      0.56      0.59       133

    accuracy                           1.00     85443
   macro avg       0.80      0.78      0.79     85443
weighted avg       1.00      1.00      1.00     85443



In [12]:
y_train.value_counts()

0    199005
1       359
Name: Class, dtype: int64

In [13]:
class_weight=dict({0:1,1:100})

In [14]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train,y_train)


RandomForestClassifier(class_weight={0: 1, 1: 100})

In [15]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85303     7]
 [   33   100]]
0.9995318516437859
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85310
           1       0.93      0.75      0.83       133

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [16]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85303     7]
 [   33   100]]
0.9995318516437859
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85310
           1       0.93      0.75      0.83       133

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [17]:
#### Under Sampling-- reduce the points of maximum labels

In [18]:
y_train.value_counts()

0    199005
1       359
Name: Class, dtype: int64

In [19]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.8)
X_train_ns,y_train_ns=ns.fit_sample(X_train,y_train)
print("The number of before the fit  {}".format(Counter(y_train)))
print("The number of after the fit  {}".format(Counter(y_train_ns)))

E:\anaconda\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


The number of before the fit  Counter({0: 199005, 1: 359})
The number of after the fit  Counter({0: 448, 1: 359})


In [20]:
0.8*436

348.8

In [21]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)


RandomForestClassifier()

In [22]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[68284 17026]
 [   13   120]]
0.8005805039617054
              precision    recall  f1-score   support

           0       1.00      0.80      0.89     85310
           1       0.01      0.90      0.01       133

    accuracy                           0.80     85443
   macro avg       0.50      0.85      0.45     85443
weighted avg       1.00      0.80      0.89     85443



##### Over Sampling

In [23]:
from imblearn.over_sampling import RandomOverSampler


In [24]:
os=RandomOverSampler(0.5)
X_train_ns,y_train_ns=os.fit_sample(X_train,y_train)
print("The number of before the fit  {}".format(Counter(y_train)))
print("The number of after the fit  {}".format(Counter(y_train_ns)))

E:\anaconda\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


The number of before the fit  Counter({0: 199005, 1: 359})
The number of after the fit  Counter({0: 199005, 1: 99502})


In [25]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [26]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

#### if the dataset is small i will definitely go with undersampling but again i will be focusing on all 
#### performance matices like recall,precision,f1-score apart from that i will also be focusing based on the domain knowledge whether i should be reducing the false positive or false negative based on that i will be select my roc score
### that is the probability value whether it should be .6 or 0.7 something like that finally i will be doing  over sampling techniques but again i will be always revolve around understanding the performance matix
#### finally if it is not working i will go with ensembled techniques like random forest , Xgboost where i can provide my class weight parameters probabily then it will perform well.

[[85301     9]
 [   29   104]]
0.9995552590615966
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85310
           1       0.92      0.78      0.85       133

    accuracy                           1.00     85443
   macro avg       0.96      0.89      0.92     85443
weighted avg       1.00      1.00      1.00     85443



#### SMOTETomek

In [27]:
from imblearn.combine import SMOTETomek

In [ ]:
os=SMOTETomek(0.5)
X_train_ns,y_train_ns=os.fit_sample(X_train,y_train)
print("The number of before the fit  {}".format(Counter(y_train)))
print("The number of after the fit  {}".format(Counter(y_train_ns)))

E:\anaconda\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)


In [ ]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

In [ ]:
#### over sampling and undersmapling are performed during model creation

#### Ensemble Techniques

In [ ]:
from imblearn.ensemble import EasyEnsembleClassifier

In [ ]:
easy=EasyEnsembleClassifier()
easy.fit(X_train,y_train)

In [ ]:
y_pred=easy.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))